# Generated by Django 5.2.11 on 2026-07-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.CharField(max_length=220, verbose_name='descricao curta')),
                ('full_description', models.TextField(verbose_name='descricao completa')),
                ('thumbnail', models.FileField(blank=True, upload_to='projects/covers/', verbose_name='imagem de capa')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('demo', models.URLField(blank=True, verbose_name='demo')),
                ('status', models.CharField(choices=[('planning', 'Planejamento'), ('development', 'Desenvolvimento'), ('beta', 'Beta'), ('finished', 'Finalizado')], default='planning', max_length=20, verbose_name='status')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='progresso')),
                ('visible', models.BooleanField(default=True, verbose_name='visivel')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-featured', '-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('color', models.CharField(default='#22d3ee', max_length=20, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'tecnologia',
                'verbose_name_plural': 'tecnologias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='projects/gallery/', verbose_name='imagem')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='legenda')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project')),
            ],
            options={
                'verbose_name': 'imagem do projeto',
                'verbose_name_plural': 'imagens do projeto',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('content', models.TextField(verbose_name='conteudo')),
                ('image', models.FileField(blank=True, upload_to='projects/updates/', verbose_name='imagem')),
                ('created_at', models.DateField(verbose_name='data')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='main.project')),
            ],
            options={
                'verbose_name': 'atualizacao',
                'verbose_name_plural': 'atualizacoes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descricao')),
                ('status', models.CharField(choices=[('done', 'Concluído'), ('in_progress', 'Em andamento'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='status')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_items', to='main.project')),
            ],
            options={
                'verbose_name': 'etapa do roadmap',
                'verbose_name_plural': 'etapas do roadmap',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.technology'),
        ),
    ]
