# Generated by Django 5.2.11 on 2026-07-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_laboratory_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('service', models.CharField(max_length=50, verbose_name='Serviço')),
                ('budget', models.CharField(max_length=30, verbose_name='Orçamento previsto')),
                ('deadline', models.CharField(max_length=30, verbose_name='Prazo')),
                ('message', models.TextField(verbose_name='Conte sobre seu projeto')),
                ('dynamic_data', models.JSONField(blank=True, default=dict, verbose_name='Perguntas adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-created_at'],
            },
        ),
    ]
