# Generated by Django 5.2.11 on 2026-07-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='nome do case')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('client_name', models.CharField(max_length=140, verbose_name='cliente')),
                ('segment', models.CharField(blank=True, max_length=80, verbose_name='segmento')),
                ('challenge', models.TextField(blank=True, verbose_name='desafio')),
                ('solution', models.TextField(blank=True, verbose_name='solução')),
                ('results', models.TextField(blank=True, verbose_name='resultado')),
                ('testimonial', models.TextField(blank=True, verbose_name='avaliação do cliente')),
                ('testimonial_author', models.CharField(blank=True, max_length=120, verbose_name='autor da avaliação')),
                ('gallery_description', models.TextField(blank=True, verbose_name='descrição da galeria')),
                ('visible', models.BooleanField(default=True, verbose_name='visível')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('technologies', models.ManyToManyField(blank=True, related_name='cases', to='main.technology')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['-featured', '-updated_at', 'title'],
            },
        ),
    ]
